import { marketSummary } from '@/data/extendedData';
import { sentimentColor } from '@/utils/format';
import { FileText, TrendingUp, TrendingDown, Minus } from 'lucide-react';
import { useApiDataWithFallback } from '@/hooks/useApiData';
import { DataStatus } from '@/components/LoadingPlaceholder';

interface ApiAnalysis {
  currency: string;
  name: string;
  score: number;
  signal: string;
  confidence: number;
  executive_summary: string;
}

function adaptToMarketSummary(raw: unknown) {
  const analyses = raw as ApiAnalysis[];
  if (!analyses?.length) return null;
  return analyses.map((a) => ({
    id: a.currency,
    currency: a.currency,
    title: `${a.currency} — ${a.signal}`,
    body: a.executive_summary,
    sentiment: a.signal.includes('Buy') ? 'bullish' as const : a.signal.includes('Sell') ? 'bearish' as const : 'neutral' as const,
    confidence: a.confidence,
    score: a.score,
  }));
}

export default function MarketSummaryPage() {
  const { data: summaries, lastUpdated, offline, refetch } = useApiDataWithFallback(
    '/api/analysis',
    marketSummary,
    300000,
    adaptToMarketSummary,
  );

  const displaySummaries = summaries ?? marketSummary;

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-slate-100">AI Market Summary</h2>
          <p className="text-sm text-slate-500">Institutional macro report generated by AI across all major currencies</p>
        </div>
        <DataStatus lastUpdated={lastUpdated} offline={offline} onRetry={refetch} />
      </div>

      {/* Executive summary banner */}
      <div className="card overflow-hidden border-accent-500/20">
        <div className="flex items-center gap-3 border-b border-ink-700/60 bg-accent-500/5 px-5 py-3">
          <FileText className="h-5 w-5 text-accent-400" />
          <h3 className="text-sm font-semibold text-slate-200">Executive Summary</h3>
          <span className="ml-auto rounded-md bg-accent-500/15 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-accent-300">AI Generated</span>
        </div>
        <div className="p-5">
          <p className="text-sm leading-relaxed text-slate-300">
            The global macro landscape remains dominated by US Dollar strength, driven by elevated interest rates, strong employment, and resilient GDP.
            The Japanese Yen continues to underperform all majors due to ultra-low rates and accommodative policy.
            The Euro faces headwinds from a deep manufacturing recession and ECB easing.
            The Swiss Franc benefits from safe-haven demand, while commodity currencies (CAD, AUD, NZD) are mixed amid diverging central bank paths.
            Market sentiment is Risk On with VIX subdued at 14.2.
          </p>
        </div>
      </div>

      {/* Per-currency reports */}
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {displaySummaries.map((s) => {
          const Icon = s.sentiment === 'bullish' ? TrendingUp : s.sentiment === 'bearish' ? TrendingDown : Minus;
          const borderColor = s.sentiment === 'bullish' ? 'border-bull-500/20' : s.sentiment === 'bearish' ? 'border-bear-500/20' : 'border-warn-500/20';
          return (
            <div key={s.id} className={`card card-hover p-4 ${borderColor}`}>
              <div className="mb-2 flex items-center gap-2">
                <Icon className={`h-4 w-4 ${sentimentColor(s.sentiment)}`} />
                <h3 className="text-sm font-bold text-slate-100">{s.title}</h3>
                <span className={`ml-auto rounded-md px-2 py-0.5 text-[10px] font-semibold uppercase ${s.sentiment === 'bullish' ? 'bg-bull-500/10 text-bull-400' : s.sentiment === 'bearish' ? 'bg-bear-500/10 text-bear-400' : 'bg-warn-500/10 text-warn-400'}`}>
                  {s.sentiment}
                </span>
              </div>
              <p className="text-xs leading-relaxed text-slate-400">{s.body}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
}
